name: Build and Publish Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For PyPI publishing
      contents: read

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"] # Adjust based on your supported versions

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important to fetch all history for tags

      - name: Get latest tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Update version in pyproject.toml
        run: |
          sed -i 's/version = "0.0.0"/version = "${{ steps.get_tag.outputs.TAG }}"/' pyproject.toml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          pip install -e .

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        if: matrix.python-version == '3.13' # Only publish once
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
